### ISSUE TITLE
Does not run?

### ISSUE THREAD

**Issue by gitboss** [parthdave93/FlutterHeadlessView#1]
I get the following error while trying to run the project  

`E/AndroidRuntime(24758): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5842)
E/AndroidRuntime(24758): 	at android.app.ActivityThread.access$1100(ActivityThread.java:199)
E/AndroidRuntime(24758): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
E/AndroidRuntime(24758): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(24758): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(24758): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/AndroidRuntime(24758): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(24758): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(24758): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/AndroidRuntime(24758): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.parthdave93.flutter_background_plugin_example.App" on path: DexPathList[[zip file "/data/app/com.parthdave93.flutter_background_plugin_example-Ph0NWcRgeKPTghub18vrpQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.parthdave93.flutter_background_plugin_example-Ph0NWcRgeKPTghub18vrpQ==/lib/x86, /data/app/com.parthdave93.flutter_background_plugin_example-Ph0NWcRgeKPTghub18vrpQ==/base.apk!/lib/x86, /system/lib]]
E/AndroidRuntime(24758): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
E/AndroidRuntime(24758): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(24758): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(24758): 	at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:50)
E/AndroidRuntime(24758): 	at androidx.core.app.CoreComponentFactory.instantiateApplication(CoreComponentFactory.java:47)
E/AndroidRuntime(24758): 	at android.app.Instrumentation.newApplication(Instrumentation.java:1120)
E/AndroidRuntime(24758): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:1061)
E/AndroidRuntime(24758): 	... 9 more
`

**Comment by parthdave93** [comment]
Sorry, It's an old code but will make it work and update with newer version.

**Comment by gitboss** [comment]
Thank you
